include: package:total_lints/package.yaml

linter:
  rules:
    prefer_relative_imports: false
    lines_longer_than_80_chars: false

    # not so important for lint package
    public_member_api_docs: false
