name: autoclose_lint
description: AutoClose_Lint is a must have feature of the AutoClose package
version: 1.0.3
repository: https://github.com/vlastachu/autoclose
issue_tracker: https://github.com/vlastachu/autoclose/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.5.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  total_lints:
