name: autoclose_flutter
description: autoclose_flutter is a package providing AutoClose functionality for the Flutter platform
version: 1.0.4
repository: https://github.com/vlastachu/autoclose
issue_tracker: https://github.com/vlastachu/autoclose/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  autoclose: 1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  total_lints:
  vm_service: ^14.2.1

flutter:
